# Generated by Django 4.0.6 on 2022-08-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_base_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
