# Generated by Django 4.0.6 on 2022-09-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='what_is_expected',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='what_we_offer',
            field=models.CharField(max_length=50),
        ),
    ]
